export const BUSINESS_TYPES = [
  "Salon",
  "Restaurant",
  "Gym",
  "Real Estate",
  "Dental Clinic",
  "Clothing Store",
  "Cafe",
  "Interior Design",
  "Other",
] as const;

export const TONES = ["Professional", "Friendly", "Luxury", "Exciting", "Urgent"] as const;

export type BusinessType = (typeof BUSINESS_TYPES)[number];
export type Tone = (typeof TONES)[number];
export type VisualMode = "upload" | "ai";
export type RegenerableSection = "instagram" | "whatsapp" | "adCopy";

/** Everything the user types into the form. */
export interface AdInput {
  businessName: string;
  businessType: BusinessType;
  product: string;
  offer: string;
  target: string;
  tone: Tone;
  campaignBrief?: string;
  visualMode?: VisualMode;
}

export interface AdPackage {
  instagram: string;
  whatsapp: string;
  adCopy: string;
  headlines: string[];
  ctas: string[];
  poster: PosterContent;
  source: "mock" | "api";
}

export type CreativeVariation = "luxury" | "bold" | "minimal";
export type PosterLayout =
  | "HERO_CENTER"
  | "SPLIT_LEFT_TEXT_RIGHT_IMAGE"
  | "SPLIT_RIGHT_TEXT_LEFT_IMAGE"
  | "FULL_BLEED_IMAGE"
  | "PRODUCT_FOCUS"
  | "MINIMAL_EDITORIAL"
  | "BOLD_PROMO"
  | "DARK_PREMIUM"
  | "CLEAN_BUSINESS"
  | "FESTIVE"
  | "SOCIAL_STORY_STYLE";
export type PosterPalette = "WARM_FOOD" | "ENERGETIC" | "REFINED" | "CALM" | "FESTIVE" | "NEUTRAL";
export type VisualSource = "CUSTOM_AI_VISUAL" | "TEMPLATE_FALLBACK" | "UPLOADED_IMAGE" | "MIXED_VISUALS";

export interface VariationOption {
  id: CreativeVariation;
  title: string;
  badge: string;
  description: string;
  themeColor: string;
}

export const CREATIVE_VARIATIONS: VariationOption[] = [
  {
    id: "luxury",
    title: "Luxury / Premium",
    badge: "👑 Editorial & Gold",
    description: "Refined serif typography, gold accents, elegant framing, and high-end aesthetic.",
    themeColor: "#D4AF37",
  },
  {
    id: "bold",
    title: "Bold / High-Conversion",
    badge: "🔥 High-Impact Sale",
    description: "High-contrast retail layout, punchy promotional badges, and vibrant marketing energy.",
    themeColor: "#FF3366",
  },
  {
    id: "minimal",
    title: "Modern / Minimal",
    badge: "✨ Swiss & Studio",
    description: "Clean studio framing, contemporary geometric typography, and balanced whitespace.",
    themeColor: "#3B82F6",
  },
];

/** A single high-converting ad concept generated by Real AI. */
export interface AdConcept {
  variationId: CreativeVariation;
  conceptName: string;
  headline: string;
  subheadline: string;
  benefit: string;
  offer: string;
  cta: string;
  caption: string;
  whatsappMessage: string;
  shortAdCopy: string;
  visualPrompt: string;
  designDirection: string;
  layoutType?: PosterLayout;
  colorDirection?: PosterPalette;
  typographyDirection?: string;
  visualHierarchy?: string;
  aiImageUrl?: string | null;
  visualSource?: VisualSource;
  imageModel?: string;
  imageGenerationMs?: number;
}

/** Complete AI campaign output returned by the local AI backend. */
export interface AdCampaign {
  analysis: {
    businessCore: string;
    targetAudience: string;
    strongestBenefit: string;
    sellingAngle: string;
  };
  concepts: AdConcept[];
  source: "api";
  visualSource?: VisualSource;
}

/** Text shown on the canvas poster itself. */
export interface PosterContent {
  businessName: string;
  mainOffer: string;
  priceLine: string;
  service: string;
  benefit: string;
  cta: string;
  location: string;
  businessType?: BusinessType;
  headline?: string;
  subheadline?: string;
  layoutType?: PosterLayout;
  colorDirection?: PosterPalette;
}

export const DEMO_INPUT: AdInput = {
  businessName: "Fitness Point Gym",
  businessType: "Gym",
  product: "Body building, be slim, gain muscle",
  offer: "₹1,499/mo — 30% OFF",
  target: "Men & women aged 20–50 in Hyderabad",
  tone: "Exciting",
  visualMode: "ai",
};
